### ISSUE TITLE
Multiple TPads in .json not drawing

### ISSUE THREAD

**Issue by aminnj** [root-project/jsroot#133]
Hi,

I'm trying to draw a canvas containing two pads by using TBufferJSON to dump the canvas from pyROOT (`r.TBufferJSON.ConvertToJSON(c1)`, where `c1` is my TCanvas), but it is not showing up properly with jsroot 5.2.0 (or 4.6.0). 

Nothing is drawn on the screen, but I can expand the json object in the tree on the left and draw the pads individually. It would be nice, however, to have them drawn together.

[Example link](http://uaf-6.t2.ucsd.edu/~namin/jsroot/index.htm?json=files/met.json) showing the problem.

The json is located [here](http://uaf-6.t2.ucsd.edu/~namin/jsroot/files/met.json) and if I do `c1.SaveAs("met.pdf")`, I get my expected result [here](http://uaf-6.t2.ucsd.edu/~namin/jsroot/files/met.pdf).

This is the js error that is thrown when trying to draw them both together I suppose:
```
d3.min.js:4 
Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '[pad=1]' is not a valid selector.
    at SVGGElement.<anonymous> (http://uaf-6.t2.ucsd.edu/~namin/jsroot/scripts/d3.min.js:4:23665)
    at pt.zf [as select] (http://uaf-6.t2.ucsd.edu/~namin/jsroot/scripts/d3.min.js:4:23869)
    at JSROOT.TPadPainter.JSROOT.TObjectPainter.svg_pad (http://uaf-6.t2.ucsd.edu/~namin/jsroot/scripts/JSRootPainter.js:1557:41)
    at JSROOT.TPadPainter.JSROOT.TObjectPainter.svg_layer (http://uaf-6.t2.ucsd.edu/~namin/jsroot/scripts/JSRootPainter.js:1563:22)
    at JSROOT.TPadPainter.AddButton (http://uaf-6.t2.ucsd.edu/~namin/jsroot/scripts/JSRootPainter.js:5399:24)
    at Object.JSROOT.Painter.drawPad [as func] (http://uaf-6.t2.ucsd.edu/~namin/jsroot/scripts/JSRootPainter.js:5506:18)
    at performDraw (http://uaf-6.t2.ucsd.edu/~namin/jsroot/scripts/JSRootPainter.js:12509:30)
    at Object.JSROOT.draw (http://uaf-6.t2.ucsd.edu/~namin/jsroot/scripts/JSRootPainter.js:12516:52)
    at JSROOT.TPadPainter.DrawPrimitive (http://uaf-6.t2.ucsd.edu/~namin/jsroot/scripts/JSRootPainter.js:4813:23)
    at Object.JSROOT.Painter.drawCanvas [as func] (http://uaf-6.t2.ucsd.edu/~namin/jsroot/scripts/JSRootPainter.js:5488:15)
```

Let me know if you need additional details!

Thank you!
Nick

**Comment by linev** [comment]
Hi Nick,

Problem is names of sub-pads.
JSROOT uses pad names in html selector and fails when name starts from the digit - not a valid identifier for HTML element. I will try to fix it.

**Comment by linev** [comment]
I apply fix for **dev** and **master** branches.
Now your canvas should work: http://jsroot.gsi.de/dev/?json=../files/tmp/met.json.gz
We plan provide bugfix release 5.2.1 later this week.

**Comment by aminnj** [comment]
Hi Sergey,

Thank you very much for this fast fix.

Nick

**Comment by linev** [comment]
Now in https://github.com/root-project/jsroot/releases/tag/5.2.1 release
