### ISSUE TITLE
Cannot install jsroot on node v8.9.1

### ISSUE THREAD

**Issue by mvala** [root-project/jsroot#138]
I am installing jsroot via 
```
npm install jsroot
```
and i am getting error
```
/home/mvala/.node-gyp/8.9.1/include/node/v8.h:3389:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/mvala/.node-gyp/8.9.1/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
make: *** [contextify.target.mk:95: Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory '/tmp/node_modules/contextify/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```
I was looking at the problem and it is in package Contextify. And i found out that it is dep of "jsdom": "^3.1.2". I installed jsdom version 4 or higher without problem. Can jsroot upgrade to jsdom >4? Latest is + jsdom@11.5.1

**Comment by linev** [comment]
I will check if higher version of jsdom can be used and let you know.

**Comment by linev** [comment]
I publish next 5.3.3 version in npm, which uses latest jsdom and mathjax-node packages.
Can you try it?

**Comment by mvala** [comment]
Yes it works. Thanks
