### ISSUE TITLE
conflicts with jsdom 10+

### ISSUE THREAD

**Issue by sekrasoft** [root-project/jsroot#149]
jsdom API has been changed. So `MakeSVG` throws the following exception:

    TypeError: jsdom.env is not a function
        at Object.JSROOT.MakeSVG (jsroot/scripts/JSRootPainter.js:5530:16)
        at jsroot/scripts/JSRootCore.js:1243:17
        at Object.JSROOT.CallBack (jsroot/scripts/JSRootCore.js:731:45)
        at normal_callback (jsroot/scripts/JSRootCore.js:1009:17)
        at Object.JSROOT.CallBack (jsroot/scripts/JSRootCore.js:731:45)
        at Object.JSROOT.loadScript (jsroot/scripts/JSRootCore.js:858:38)
        at Object.JSROOT.loadScript (jsroot/scripts/JSRootCore.js:898:17)
        at Object.JSROOT.loadScript (jsroot/scripts/JSRootCore.js:898:17)

Specifying jsdom < v10 in package.json makes JSROOT work:

    -    "jsdom": "*",
    +    "jsdom": "< 10.0.0",

[sjrd posted this workaround](https://github.com/jsdom/jsdom/issues/1820#issuecomment-297198316) for the problem:

    var jsdom;
    try {
      jsdom = require("jsdom/lib/old-api.js"); // jsdom >= 10.x
    } catch (e) {
      jsdom = require("jsdom"); // jsdom <= 9.x
    }

**Comment by linev** [comment]
Hi,

Thanks for the info.

If I change package.json as you proposed, do I need to apply second workaround?

**Comment by sekrasoft** [comment]
> If I change package.json as you proposed, do I need to apply second workaround?
Changing package.json is enough.

**Comment by linev** [comment]
I decide to use both workarounds.
I am not sure that happens when several jsdom packages are installed and simple `require("jsdom")` invoked.
In next weeks I will provide patch JSROOT release

**Comment by linev** [comment]
Sorry for some delay - now fixed in [5.4.1](https://github.com/root-project/jsroot/releases/tag/5.4.1) release
